lang: en  #Support en,cn
maxRooms: 5
spawnWorldSeed: 759242905499401623
canGameStartWhenRoomNotFull: true #for test only
worldNamePrefix: enderkill_world
spawnWorldName: enderkill_world_spawn
initMoneyType: EMERALD
initMoneyAmount: 30
voteAbstainSign: -1
teleportDelay: 200 #ticks
teamLeaderVoteTimeout: 6000 #ticks
teamLeaderDieVoteTimeout: 600 #ticks
skillLaunchVoteTimeout: 600 #ticks
putToDeathVoteTimeout: 6000 #ticks
voteToDieDelay: 200 #ticks
duelVoteTimeout: 600 #ticks
teamLeaderSummonDelay: 600 #ticks
rewardType: IRON_INGOT
rewardAmount: 64
rewardExp: 999
gameOverDelay: 200 #ticks
deleteWorldsAfterGame: true
cleanOutInventoryBeforeGame: true
cleanOutInventoryAfterGame: true
