name: EnderKiller
version: 0.1
author: UndefinedStudio
main: com.udstu.enderkiller.Main
depend:
website: http://www.udstu.com
commands:
  ek:
    description: This is EnderKiller.
    usage: /<command>
    aliases: [enderkiller]