name: EnderKiller
version: 0.2
author: UndefinedStudio
main: com.udstu.enderkiller.Main
depend:
website: http://www.udstu.com
commands:
  ek:
    description: Show the commands available of EnderKiller.
    usage: /<command> [arguments]
    aliases: [enderkiller]
